### ISSUE TITLE
Add User domain

### ISSUE THREAD

**Issue by MikalaiBezmen** [AlexStasko/pdp#3]
As a mentor, i want to have a User domain object:
1) should have next fields:
- String firstName
- String lastName
- String password
- String email
- Long id (for this would be better to create new common domain BaseEntity, but do not specify the type of field - use generic)
- LocalDate createdDate (create separate domain for this 5 fields - StoredEntity)
- LocalDate updatedDate
- String createdByUser
- String updatedByUser
- int version
2) Implement Builder for this class

**Comment by AlexStasko** [comment]
Should this class be in `repository` module?

**Comment by MikalaiBezmen** [comment]
no, I think in would be better to create one more module with the next name: "domain"

**Comment by AlexStasko** [comment]
Do I need to overwrite `equals` and `hashCode`?

**Comment by MikalaiBezmen** [comment]
`equals` and `hashCode` should be overwritten

**Comment by AlexStasko** [comment]
Should I cover these classes with unit tests?
